## Final Project Submission

Please fill out:
* Student name: 
* Student pace: self paced / part time / full time
* Scheduled project review date/time: 
* Instructor name: 
* Blog post URL:


Possible questions

Does area income effect price of houses

Does grade have an effect on housing price

Does property size effect housing price

Does Age of property effect price

In [20]:
#find lat and long of city center then subtract out lat and long form it to find the difference 
# weak correlation to test in model Floor waterfront view and grade 

In [21]:
#Importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
import numpy as np
from datetime import datetime
import statsmodels.formula.api as smf
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from scipy import stats
import math
from PIL import Image

In [39]:
df2 = pd.read_csv("data/kc_house_data_clean.csv")

In [23]:
df2

Unnamed: 0  date      price  bedrooms  bathrooms  sqft_living  \
0               0   164   221900.0         3       1.00         1180   
1               1    52   205425.0         2       1.00          880   
2               2    76   445000.0         3       2.25         2100   
3               3   146   236000.0         3       1.00         1300   
4               4   292   170000.0         2       1.00          860   
...           ...   ...        ...       ...        ...          ...   
21415       21415   154  2720000.0         4       3.25         3990   
21416       21416    84  1950000.0         4       3.50         4065   
21417       21417   345  2250000.0         5       5.25         3410   
21418       21418   195  2900000.0         5       4.00         5190   
21419       21419   292  1870000.0         4       3.75         3790   

       sqft_lot  floors  waterfront  view  ...  yr_built  yr_renovated  \
0          5650     1.0           0     4  ...      1955           0.0   
1          6780     1.0           0     4  ...      1945           0.0   
2          8201     1.0           0     0  ...      1967           0.0   
3          5898     1.0           0     4  ...      1961           0.0   
4          5265     1.0           0     4  ...      1931           0.0   
...         ...     ...         ...   ...  ...       ...           ...   
21415     18115     2.0           0     4  ...      1989           0.0   
21416     18713     2.0           0     4  ...      1987           0.0   
21417      8118     2.0           0     4  ...      2006           0.0   
21418     14600     2.0           0     2  ...      2013           0.0   
21419      8797     2.0           0     4  ...      2006           0.0   

       zipcode      lat     long  sqft_living15  sqft_lot15    Income  \
0        98178  47.5112 -122.257           1340        5650  113555.0   
1        98178  47.5009 -122.248           1190        6780  113555.0   
2        98178  47.5091 -122.244           2660        8712  113555.0   
3        98178  47.5053 -122.255           1320        7619  113555.0   
4        98178  47.5048 -122.272           1650        8775  113555.0   
...        ...      ...      ...            ...         ...       ...   
21415    98039  47.6177 -122.229           3450       16087    7190.0   
21416    98039  47.6209 -122.237           3070       18713    7190.0   
21417    98039  47.6295 -122.236           3410       16236    7190.0   
21418    98039  47.6102 -122.225           3840       19250    7190.0   
21419    98039  47.6351 -122.236           2660       12150    7190.0   

       year_sold  house_age_at_sale  
0           2014               59.0  
1           2014               69.0  
2           2014               47.0  
3           2014               53.0  
4           2015               84.0  
...          ...                ...  
21415       2014               25.0  
21416       2014               27.0  
21417       2015                9.0  
21418       2014                1.0  
21419       2015                9.0  

[21420 rows x 24 columns]

In [24]:
df2 =df2.drop(["Unnamed: 0"], axis = 1)

In [25]:
df2

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0       164   221900.0         3       1.00         1180      5650     1.0   
1        52   205425.0         2       1.00          880      6780     1.0   
2        76   445000.0         3       2.25         2100      8201     1.0   
3       146   236000.0         3       1.00         1300      5898     1.0   
4       292   170000.0         2       1.00          860      5265     1.0   
...     ...        ...       ...        ...          ...       ...     ...   
21415   154  2720000.0         4       3.25         3990     18115     2.0   
21416    84  1950000.0         4       3.50         4065     18713     2.0   
21417   345  2250000.0         5       5.25         3410      8118     2.0   
21418   195  2900000.0         5       4.00         5190     14600     2.0   
21419   292  1870000.0         4       3.75         3790      8797     2.0   

       waterfront  view  condition  ...  yr_built  yr_renovated  zipcode  \
0               0     4          0  ...      1955           0.0    98178   
1               0     4          2  ...      1945           0.0    98178   
2               0     0          0  ...      1967           0.0    98178   
3               0     4          0  ...      1961           0.0    98178   
4               0     4          0  ...      1931           0.0    98178   
...           ...   ...        ...  ...       ...           ...      ...   
21415           0     4          2  ...      1989           0.0    98039   
21416           0     4          2  ...      1987           0.0    98039   
21417           0     4          0  ...      2006           0.0    98039   
21418           0     2          0  ...      2013           0.0    98039   
21419           0     4          0  ...      2006           0.0    98039   

           lat     long  sqft_living15  sqft_lot15    Income  year_sold  \
0      47.5112 -122.257           1340        5650  113555.0       2014   
1      47.5009 -122.248           1190        6780  113555.0       2014   
2      47.5091 -122.244           2660        8712  113555.0       2014   
3      47.5053 -122.255           1320        7619  113555.0       2014   
4      47.5048 -122.272           1650        8775  113555.0       2015   
...        ...      ...            ...         ...       ...        ...   
21415  47.6177 -122.229           3450       16087    7190.0       2014   
21416  47.6209 -122.237           3070       18713    7190.0       2014   
21417  47.6295 -122.236           3410       16236    7190.0       2015   
21418  47.6102 -122.225           3840       19250    7190.0       2014   
21419  47.6351 -122.236           2660       12150    7190.0       2015   

       house_age_at_sale  
0                   59.0  
1                   69.0  
2                   47.0  
3                   53.0  
4                   84.0  
...                  ...  
21415               25.0  
21416               27.0  
21417                9.0  
21418                1.0  
21419                9.0  

[21420 rows x 23 columns]

Initial Model

In [26]:
y = df2["price"]
X = df2.drop("price", axis=1)

In [27]:
model = sm.OLS(y, sm.add_constant(X.astype(float)), missing = "drop").fit()
results = model.summary()
print(results)

                            OLS Regression Results                            
Dep. Variable:                  price   R-squared:                       0.683
Model:                            OLS   Adj. R-squared:                  0.683
Method:                 Least Squares   F-statistic:                     2200.
Date:                Wed, 05 Jan 2022   Prob (F-statistic):               0.00
Time:                        09:26:57   Log-Likelihood:            -2.9256e+05
No. Observations:               21420   AIC:                         5.852e+05
Df Residuals:                   21398   BIC:                         5.853e+05
Df Model:                          21                                         
Covariance Type:            nonrobust                                         
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const             -5.502e+07   1.18e+0

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(17136, 22)
(4284, 22)
(17136,)
(4284,)


In [30]:
df2 = df2.to_numpy()

In [31]:
y = df2[:, 0]
y

array([164.,  52.,  76., ..., 345., 195., 292.])

In [32]:
X = df2[:,1:]
X

array([[2.21900e+05, 3.00000e+00, 1.00000e+00, ..., 1.13555e+05,
        2.01400e+03, 5.90000e+01],
       [2.05425e+05, 2.00000e+00, 1.00000e+00, ..., 1.13555e+05,
        2.01400e+03, 6.90000e+01],
       [4.45000e+05, 3.00000e+00, 2.25000e+00, ..., 1.13555e+05,
        2.01400e+03, 4.70000e+01],
       ...,
       [2.25000e+06, 5.00000e+00, 5.25000e+00, ..., 7.19000e+03,
        2.01500e+03, 9.00000e+00],
       [2.90000e+06, 5.00000e+00, 4.00000e+00, ..., 7.19000e+03,
        2.01400e+03, 1.00000e+00],
       [1.87000e+06, 4.00000e+00, 3.75000e+00, ..., 7.19000e+03,
        2.01500e+03, 9.00000e+00]])

In [38]:
data_transformation = preprocessing.StandardScaler()
data = data_transformation.fit_transform(X_train)
data

array([[ 0.37862352,  0.69645624,  1.14311312, ..., -0.27497618,
        -0.69322426, -0.177961  ],
       [-0.56966941, -0.4095093 , -0.47897916, ..., -0.27497618,
        -0.69322426,  0.84321561],
       [-0.87968826,  0.69645624,  0.16985775, ..., -0.37779891,
        -0.69322426, -0.92682385],
       ...,
       [-0.04081374, -1.51547483, -0.47897916, ...,  2.26723645,
        -0.69322426,  0.77513717],
       [ 1.52751687,  0.69645624, -0.15456071, ..., -0.90128002,
         1.44253463,  0.40070575],
       [ 1.59134428, -0.4095093 ,  0.4942762 , ..., -0.82875388,
         1.44253463, -0.96086307]])

In [34]:
model = LinearRegression().fit(X_train, y_train)

In [35]:
accuracy = model.score(X_train, y_train)
accuracy

0.6860009284435378

In [37]:
test_accuracy = model.score(j.transform(X_test), y_test)
test_accuracy

NameError: name 'j' is not defined